<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>RENDER | <?php echo $this->translate( "pageHeading", "common" ); ?> | <?php echo $this->translate( "articleMonitorHeading" ); ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/alg_html.css" />
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery-1.8.0.min.js"></script>
	</head>

	<body>
		<div class="alg-container box-shadow">
<?php include( APP_PATH . "../templates/pageHeading.phtml" ); ?>

			<div style="padding-top: 10px;">
				<h2><?php echo $this->translate( "articleMonitorHeading" ); ?></h2>
				<p><?php echo $this->translate( "articleMonitorDesc" ); ?></p>
				<h4><?php echo $this->translate( "instHeading" ); ?></h4>
				<p><?php echo $this->translate( "instDesc" ); ?></p>
				<div class="box-shadow" style="padding-left: 20px;">
					<pre><code><?php
echo htmlentities("importScript('User:Kai_Nissen_(WMDE)/js/Artikelmonitor.js');");
?></code></pre>
				</div>
				<p></p>
			</div>
<?php require( 'disclaimer.phtml' ); ?>
		</div>
	</body>
</html>
